version: '3'
services:
  app:
    build: .
    command: python -u app/server.py
    ports:
     - "5000:5000"
    volumes:
     - .:/project
    links:
      - db
  db:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'